// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_16YpeaGheT3kFVYqXxYqj-r4bRo_Bl0',
    appId: '1:892421261757:web:a739cc7dcdf0f4795fead4',
    messagingSenderId: '892421261757',
    projectId: 'lifeosapp-af6fb',
    authDomain: 'lifeosapp-af6fb.firebaseapp.com',
    storageBucket: 'lifeosapp-af6fb.firebasestorage.app',
    measurementId: 'G-LGSBQXBKFM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB51yk4M9j4f2_LX0vuAScL2czGcWedxn0',
    appId: '1:892421261757:android:b30cb728613766935fead4',
    messagingSenderId: '892421261757',
    projectId: 'lifeosapp-af6fb',
    storageBucket: 'lifeosapp-af6fb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBooFvgkEdaM0Bca_tm5vb2i-p4ASH0eg0',
    appId: '1:892421261757:ios:80edf37b887e13cd5fead4',
    messagingSenderId: '892421261757',
    projectId: 'lifeosapp-af6fb',
    storageBucket: 'lifeosapp-af6fb.firebasestorage.app',
    androidClientId: '892421261757-rlm6lqsu7eetubvqp3nmkmgnp4q9kd3r.apps.googleusercontent.com',
    iosClientId: '892421261757-e83h14spgptq3ank4qj83n1ilo8t2gji.apps.googleusercontent.com',
    iosBundleId: 'com.example.lifeos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBooFvgkEdaM0Bca_tm5vb2i-p4ASH0eg0',
    appId: '1:892421261757:ios:80edf37b887e13cd5fead4',
    messagingSenderId: '892421261757',
    projectId: 'lifeosapp-af6fb',
    storageBucket: 'lifeosapp-af6fb.firebasestorage.app',
    androidClientId: '892421261757-rlm6lqsu7eetubvqp3nmkmgnp4q9kd3r.apps.googleusercontent.com',
    iosClientId: '892421261757-e83h14spgptq3ank4qj83n1ilo8t2gji.apps.googleusercontent.com',
    iosBundleId: 'com.example.lifeos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_16YpeaGheT3kFVYqXxYqj-r4bRo_Bl0',
    appId: '1:892421261757:web:d0cecec3bb44e7565fead4',
    messagingSenderId: '892421261757',
    projectId: 'lifeosapp-af6fb',
    authDomain: 'lifeosapp-af6fb.firebaseapp.com',
    storageBucket: 'lifeosapp-af6fb.firebasestorage.app',
    measurementId: 'G-6NRVRCB6D6',
  );

}